# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageviewrestriction',
            name='restriction_type',
            field=models.CharField(choices=[('none', 'Public'), ('login', 'Private, accessible to logged-in users'), ('password', 'Private, accessible with the following password'), ('groups', 'Private, accessible to users in specific groups'), ('fee_payed', 'Private, accessible only to users with fee payed for current year')], max_length=20),
        ),
    ]
